package ra.btc.rpc.blockchain;

import ra.btc.rpc.RPCRequest;

import java.util.List;
import java.util.Map;

/**
 * Verifies that a proof points to a transaction in a block, returning the transaction it commits to and throwing an RPC error if the block is not in our best chain
 */
public class VerifyTxOutProof extends RPCRequest {
    public static final String NAME = "verifytxoutproof";

    // Request
    public String proof; // The hex-encoded proof generated by gettxoutproof

    // Response
    public List<String> txIds;

    public VerifyTxOutProof() {super(NAME);}

    public VerifyTxOutProof(String proof) {
        super(NAME);
        this.proof = proof;
    }

    @Override
    public Map<String, Object> toMap() {
        params.add(proof);
        return super.toMap();
    }

    @Override
    public void fromMap(Map<String, Object> m) {
        if(m.size() > 0) {
            for(Object obj : m.values()) {
                txIds = (List<String>)obj;
                break;
            }
        }
    }
}
